spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jxoj?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
  rabbitmq:
    host: 192.168.23.161
    port: 5672
    username: admin
    password: guest
    virtual-host: my_vhost
    #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
oj:
  work-path: D:/work
  user-name: 1246269795@qq.com
  pass-word: sjh20000903
server:
  port: 8989